require 'base64'
require 'lockfile'
require 'openssl'
require 'yaml'

require 'coquelicot/auth'
require 'coquelicot/stored_file'
require 'coquelicot/depot'
require 'coquelicot/configure'
require 'coquelicot/app'
